### ISSUE TITLE
Implementar i18n -- language switcher

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/AED#12]
Revisar si esto está implementado en el diseño sino pedir que nos lo hagan para colocarlo y maquetarlo.

Back: implementarlo y que se imprima en pantalla.
Front: dar amor.

**Comment by interdruper** [comment]
Propongo postponerlo junto a #11

**Comment by fjgarlin** [comment]
Creo que https://github.com/AsociacionDrupalES/AED/issues/11 englobaría también este issue, así que lo cierro.
