### ISSUE TITLE
Revisar y actualizar los textos estáticos de la web.

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/AED#14]
Muchas secciones tienen un texto inmutable como por ejemplo 

![image](https://cloud.githubusercontent.com/assets/1402913/26443012/0b223b22-4137-11e7-98cf-d59f5a142129.png)

Hay que echarle un vistazo y actualizarlos.

**Comment by fjgarlin** [comment]
That's part of a view and it was updated in #50 , so closing this issue.
