### ISSUE TITLE
Rellenar humans.txt

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/AED#15]

**Comment by fjgarlin** [comment]
I'm sure that there are more, but for now I added the ones in https://github.com/AsociacionDrupalES/AED/graphs/contributors

Added as part of https://github.com/AsociacionDrupalES/AED/pull/130

**Comment by fjgarlin** [comment]
https://github.com/AsociacionDrupalES/AED/pull/130/commits/9d4208a336f903731940e260a7008dd9c511ff3b
