### ISSUE TITLE
Habilitar y configurar pathauto

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/AED#18]

**Comment by capynet** [comment]
Resuelto. Desplegado en prod.

**Comment by capynet** [comment]
Vuelvo a abrir. Pathauto ya está habilitado y configurado en prod pero al generar los alias en masa informa que lo hizo pero cuando se verifica se puede ver que no se han creado en absoluto.

Esto pasa en dev y prod. hace falta revisar a ver que pasa.

**Comment by interdruper** [comment]
It may be related to this [issue](https://www.drupal.org/node/2778785).

@juampynr hinted a workaround in this [issue](https://www.drupal.org/node/2665788), perhaps he has more info about this problem.

**Comment by capynet** [comment]
Actualmente este problema ya no existe \o/

Cierro!
