### ISSUE TITLE
Al slider de la home no le funciona el autoplay

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/AED#20]
/admin/config/media/slick/home_style
Ahora mismo está puesto en 5s pero no pasa a la siguiente slide.

Esto es de baja prioridad porque solo pasa cuando estas logueado como admin (no me fije como usuario normal).

**Comment by fjgarlin** [comment]
Con la actualización de módulos en https://github.com/AsociacionDrupalES/AED/pull/130 esto ya no pasa más.
