### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/AED#24]
El Favicon que aparece en la web sigue siendo el Druplicon

**Comment by capynet** [comment]
Y no mola que sea un druplicon para la AED?

**Comment by fjgarlin** [comment]
El Druplicon está bien en mi opinión. Aún así, he añadido uno de la AED en https://github.com/AsociacionDrupalES/AED/pull/130, que se desplegará después de reyes. Si no gusta, se puede cambiar de vuelta.

**Comment by fjgarlin** [comment]
https://github.com/AsociacionDrupalES/AED/pull/130/commits/71d7f3bd718e641ae4475089dc99b5a6a3365951
