### ISSUE TITLE
Revisar filtros expuestos en los videos

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/AED#25]
Hay algunos filtros que igual no tienen sentido:

![screenshot from 2017-05-26 11-22-39](https://cloud.githubusercontent.com/assets/877002/26488963/c11cce28-4205-11e7-88f7-2e2d6898d09b.png)

El de ponentes igual tambien habria que plantearse si lo queremos.

**Comment by capynet** [comment]
Gracias!, arreglado y de paso he quitado la faceta del ponente. es verdad que no aporta mucho.
