### ISSUE TITLE
Añadir los grupos locales faltantes

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/AED#26]
Para la release creamos 6 pero hay bastantes mas https://groups.drupal.org/node/186379

Crearlos con su respectiva imagen.

**Comment by interdruper** [comment]
Done.

See follow-up #52.

**Comment by capynet** [comment]
No era eso exactamente. En la home se muestran 6 y cuando le das al botón "Ver todos" te lleva a la pagina en la que recién ahí se tienen que mostrar todos los grupos que faltaban.

**Comment by interdruper** [comment]
Todos los grupos activos ya están dados de alta.
