### ISSUE TITLE
Quitar el paginador en "Empresas colaboradoras"

### ISSUE THREAD

**Issue by kikoalonsob** [AsociacionDrupalES/AED#27]
Creo que lo más justo es que no hubiera paginador en esta página. Alguna empresa puede sentirse discriminada al no aparecer en primera página.

**Comment by interdruper** [comment]
Hecho en PRO. Se ha quitado el paginador y la ordenación de las empresas tanto en la landing como en el bloque de la home. La ordenación de las empresas ahora es aleatoria.

Pending de que @capynet comitee la vista al repo.

**Comment by interdruper** [comment]
Committed 28a9b69
