### ISSUE TITLE
Auditoria SEO

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/AED#31]

**Comment by interdruper** [comment]
- [Install & config Metatag module ]
- [Install & config Redirect module ]

**Comment by asieraed** [comment]
Hola Marcelo te paso el informe básico SEO cuando realicéis los cambios me avisas y hago un seguimiento. Espero que os sirva. Saludos
[5xx_server_errors_.xls.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101360/5xx_server_errors_.xls.xlsx)
[resolucion www.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101363/resolucion.www.xlsx)
[enlaces externos rotos.xls.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101365/enlaces.externos.rotos.xls.xlsx)
[imagenes rotas.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101364/imagenes.rotas.xlsx)
[Títulos duplicados.xls.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101361/Titulos.duplicados.xls.xlsx)
[contenido duplicado.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101362/contenido.duplicado.xlsx)
[enlaces internos rotos.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101366/enlaces.internos.rotos.xlsx)
[mixed_content.xls.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101368/mixed_content.xls.xlsx)
[imagen externa rota.xls.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101367/imagen.externa.rota.xls.xlsx)
[advertencias-atributos no follow.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101370/advertencias-atributos.no.follow.xlsx)
[advertencia - no tiene metadescripciones.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101369/advertencia.-.no.tiene.metadescripciones.xlsx)
[Advertencia - contenido pobre.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101371/Advertencia.-.contenido.pobre.xlsx)
[no tienen encabezado h1.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101372/no.tienen.encabezado.h1.xlsx)
[62 links on HTTPS pages leads to HTTP page.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101373/62.links.on.HTTPS.pages.leads.to.HTTP.page.xlsx)
[no tienen suficiente texto en las etiquetas de título.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101374/no.tienen.suficiente.texto.en.las.etiquetas.de.titulo.xlsx)
[titulos demasiado largos.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101376/titulos.demasiado.largos.xlsx)
[tienen más de un encabeado h1.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101375/tienen.mas.de.un.encabeado.h1.xlsx)
[no tienen atributos alt.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101377/no.tienen.atributos.alt.xlsx)
[redireccionamiento temporal.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101378/redireccionamiento.temporal.xlsx)
[Sitemap.xml no encontrado.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101379/Sitemap.xml.no.encontrado.xlsx)

[prominencia .xlsx](https://github.com/AsociacionDrupalES/AED/files/1101380/prominencia.xlsx)




[GTmetrix-report.pdf](https://github.com/AsociacionDrupalES/AED/files/1101381/GTmetrix-report.pdf)
[errores 404.xlsx](https://github.com/AsociacionDrupalES/AED/files/1101382/errores.404.xlsx)

[Palabras organicas aed .pdf](https://github.com/AsociacionDrupalES/AED/files/1101383/Palabras.organicas.aed.pdf)
[Revisión SEO AED.pdf](https://github.com/AsociacionDrupalES/AED/files/1101384/Revision.SEO.AED.pdf)

**Comment by asieraed** [comment]
Empieza por el archivo Revisión-SEO-AED.pdf  es la guía incluye todo los enlaces que vinculas con los informes excel sobre datos extraidos de la web.  Estamos en contacto.

**Comment by interdruper** [comment]
Gracias @asieraed . Sí, hay muchas cosas que mejorar. ¿Nos podrías echar una mano contribuyendo en esto? Entiendo que muchas cosas se pueden mejorar con el módulo Metatag y con acceso a los contenidos. 
Para cambiar la configuración de Metatag, habría que clonar el repo a local, exportar la configuración de Metatag y hacer un pull request. Todo está explicado en la wiki, pero si te animas te podemos ayudar en esto. En cuanto a los contenidos (tags, keyword...) sería darte permiso de edición.

**Comment by asieraed** [comment]
Hola @interdruper,
Mi perfil no es desarrollador, más bien siteBuilding. He colaborado con la auditoría SEO. Si queréis más adelante, una vez realicéis los cambios, puedo ir revisando y realizar un seguimiento.
