### ISSUE TITLE
Sanitize database script: adding some missing tables to truncate

### ISSUE THREAD

**Issue by interdruper** [AsociacionDrupalES/AED#37]
Follow up from #33 and #34

**Comment by interdruper** [comment]
A couple of non-fatal errors appeared while running the script:

- adding 'echo' in the drush commands for each table
- removing some redundant commands
- reordering command sequence

**Comment by capynet** [comment]
@interdruper lo he probado y ya casi no da errores pero si que todavía me da uno:

![image](https://user-images.githubusercontent.com/1402913/27260787-ff5954fe-5434-11e7-96af-0a6137784276.png)

Lo revisas a ver si es un error critico?
El resto lo veo bien.

**Comment by interdruper** [comment]
@capynet No entiendo, a mí no me falla en ese campo... (en cualquier caso tampoco importa demasiago si esa tabla se quedara sin sanitizar, son los perfiles píblicos en drupal.org):
![image](https://user-images.githubusercontent.com/12266539/27356993-db106d0c-5610-11e7-9195-36f25a41c0b6.png)

Para no molestarte más, en el pull request  he subido también la BBDD ya sanitizada a dev, solo faltaría el merge con la master.

**Comment by interdruper** [comment]
Reabro issu
