### ISSUE TITLE
Menu block '+ sobre Drupal': fix style when more than 4 items are used

### ISSUE THREAD

**Issue by interdruper** [AsociacionDrupalES/AED#48]

**Comment by interdruper** [comment]
![48-drupal links-menu-block-styling1](https://user-images.githubusercontent.com/12266539/27185374-69a0040e-51e5-11e7-9c66-20c96759a347.jpg)

It should be something like this:
![48-drupal links-menu-block-styling2](https://user-images.githubusercontent.com/12266539/27185527-ed87d94a-51e5-11e7-8dd2-b44f2b4587c1.jpg)

**Comment by fjgarlin** [comment]
The first two links point to no longer maintained sites, the "groups" link will soon be deprecated, so I'd argue that we don't need to worry about having +4 links for now. 

It's an easy change but not needed at the moment in my opinion.
