### ISSUE TITLE
Sección empresas colaboradoras

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/AED#5]
- En la sección de empresas colaboradoras (/partners) hay que reodernar el listado de años para que vaya del año actual hacia abajo.

- Solo deberían verse los años que tengan alguna empresa. Por ejemplo del 2018 al 2020 no hay empresas y no tiene sentido que se muestren.

**Comment by interdruper** [comment]
- Debería aparecer seleccionado por defecto el año actual, para que se muestren las colaboradoras actuales

- Idem en el bloque de la home, y que sea sin slider. Tal como está ahora se privilegia a la primera.

**Comment by DavidHernandez** [comment]
Faltan los anyos 2017 y 2018

![screenshot from 2017-05-26 11-19-01](https://cloud.githubusercontent.com/assets/877002/26488819/2e6f32be-4205-11e7-9b27-9da2dd9d1c67.png)

**Comment by interdruper** [comment]
Resuelto todo lo anterior en PRO, pending de que @capynet comiteee la vista al repo

**Comment by interdruper** [comment]
Pendiente el tema de los profiles de empresa de la web antigua, tan solo se migró la primera frase al campo de slogan.

Lo que propongo:

- añadir el campo Body al CT de Partners para que las empresas puedan tener una descripción amplia
- añadir un campo enlace al CT de Partners para poner el enlace al profile de drupal.org
- que cada empresa pueda editar su propia ficha (solo la suya y solo editar). Así no dependen de los admins de la web. Para ello habría que crear un nuevo rol y asignárselo al usuario responsable de cada empresa, con un único permiso adicional 'Partner: Edit own content' (y ponerle como owner de su ficha, claro)

Me puedo encargar yo de esto.

**Comment by capynet** [comment]
Desplegado en dev y en prod.

**Comment by interdruper** [comment]
Cierro y abro otro issue con lo pendiente
