### ISSUE TITLE
Outdated origins

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/AED#50]
The origins of the association page is outdated, showing a board of more than 3 years ago: https://asociaciondrupal.es/content/origenes

**Comment by capynet** [comment]
Ya estaba reportado aquí: https://github.com/AsociacionDrupalES/AED/issues/14 :D

**Comment by isholgueras** [comment]
He actualizado los orígenes con este último año. Si alguien más quiere actualizar los de otro año... ahora mismo no estoy seguro de la composición de la junta de cada año
