### ISSUE TITLE
Provide /rss.xml feed for articles/news

### ISSUE THREAD

**Issue by interdruper** [AsociacionDrupalES/AED#55]
Enable and config the feed display in the 'articles' view.

**Comment by fjgarlin** [comment]
Added in https://github.com/AsociacionDrupalES/AED/pull/130

**Comment by fjgarlin** [comment]
https://github.com/AsociacionDrupalES/AED/pull/130/commits/c734bcf758e4f7d29344185234850722ecb76c2d
