### ISSUE TITLE
Automatic post to Twitter when a new article or video is published

### ISSUE THREAD

**Issue by interdruper** [AsociacionDrupalES/AED#56]
Install and configure the following modules:

- [ ] [Social API](https://www.drupal.org/project/social_api)
- [ ] [Social Auth Twitter](https://www.drupal.org/project/social_auth_twitter)

If anyone knows a better or easier approach, comments are welcome.

**Comment by fjgarlin** [comment]
I think that the social networks are managed independently by some community members, so closing this issue unless it is requested/discussed again
