### ISSUE TITLE
Falta poner pagos recurrentes.

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/AED#6]

**Comment by capynet** [comment]
Estoy en ello.

**Comment by interdruper** [comment]
Meanwhile the issue is fixed, at least a link to the paypal payment should be provided anyway.

**Comment by interdruper** [comment]
@capynet cómo podemos desatascar esto? No parece muy seria una asociación a la que no hay forma de asociarse y/o renovar la cuota... Copio al presi... @alvar0hurtad0

**Comment by capynet** [comment]
Que gustazo cerrar este issue :dancer:
