### ISSUE TITLE
Add a private 'Drupal paid services' section for associates and company partners

### ISSUE THREAD

**Issue by interdruper** [AsociacionDrupalES/AED#66]
Similar to https://www.drupal.org/paid-services:

1. Companies or individuals looking for paid Drupal services may upload an opportunity ad in the forum (obviously always related to Drupal). All the ads will be moderated, except those ones from associates and partners. The ads will be public and they should include a way of contact and the required location (or remote), since no comments or responses will be allowed.
2. Associates will have the option to subcribe/unsubscribe to the forum and they will receive mail alerts when new ads are published.

The idea under this proposal is to offer additional benefits from being associated to AED, mainly thinking in freelancers and people looking for a new job.

**Comment by interdruper** [comment]
The feature will be implemented based in the following modules:

- [ ] Forum (core)
- [ ] Flag
- [ ] Message

For the sake of simplicity, no additional content types or views/filters will be generated. The ads will be shown as a list in chronological order by the Forum module.

A new page and new main menu entry will be used. A custom 'Call to action' block can be created for the homepage (similar to 'Hazte socio').

Minimal theming may be required.

**Comment by fjgarlin** [comment]
My 2c on this is that the volume of work needed for this vs the number of members/companies that we have in here doesn't justify the effort and it might end up being mostly "empty" (how many offers will we get a month?) 

Even a dedicated platform like https://jobs.drupal.org/ has very low volume and there are also Drupal slack channels dedicated to job finding/

I'm closing this for now but if you want to re open and continue the discussion we can do it.
