### ISSUE TITLE
Improve the members view

### ISSUE THREAD

**Issue by interdruper** [AsociacionDrupalES/AED#67]
https://asociaciondrupal.es/members

- alphabetical order
- exposed filter search box
- show who is member for the current year

**Comment by capynet** [comment]
He tenido que revertir el punto "show who is member for the current year". Estaba impreso a pelo en un tpl y estaba causando problemas en otros lados. Si se quiere añadir hacerlo mediante un extra field en el view mode "compact" de la entidad user por favor.

**Comment by fjgarlin** [comment]
The first two items were addressed. The last item can be seen by accessing user profiles.

Closing for now, if we need further improvements we can open a follow up.
