### ISSUE TITLE
Al rellenar un form de contacto no se enía una copia por email a la AED

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/AED#75]
Creo que van por aquí los tiros:

Warning: implode(): Invalid arguments passed in Drupal\contact\MailHandler->sendMailMessages() (line 100 of core/modules/contact/src/MailHandler.php).

**Comment by capynet** [comment]
Instalo swiftmailer y lo configuro con mailgun para evitar problemas con el smtp del servidor.

**Comment by luismagr** [comment]
Este es el mensaje que se muestra al tratar de recuperar la contraseña.
![image](https://user-images.githubusercontent.com/2010864/35562259-1c44665a-05b3-11e8-8326-4793e4009b72.png)

**Comment by alvar0hurtad0** [comment]
Vaya, es otra issue, lo siento culpa mía.

Abro otra.
