### ISSUE TITLE
Crear filtro anti-spam

### ISSUE THREAD

**Issue by samuelsolis** [AsociacionDrupalES/AED#87]
Desde la página de contacto está llegando muchísimo spam.

Habría que poner algún tipo de filtro o similar.

**Comment by fjgarlin** [comment]
Estoy añadiendo https://www.drupal.org/project/captcha en el pull request https://github.com/AsociacionDrupalES/AED/pull/130. 

Se desplegará después de reyes. Cierro issue.

**Comment by fjgarlin** [comment]
https://github.com/AsociacionDrupalES/AED/pull/130/commits/e7cb74880f6d11c200e6d5d8dc8678c7eb21be1b
